---
driver:
  name: docker
  customize:
    name: starbrain
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.2
  encrypted_data_bag_secret_key_path: test/fixture_data_bag_secret
  data_bags_path: test/fixtures/data_bags
  environments_path: test/fixtures/environments
  roles_path: roles
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
    driver_config:
      dockerfile: test/Dockerfile
      # privileged: true # Needed by systemd to access cgroups
      # run_command: /usr/sbin/init # Start systemd as root process
      # run_command: /usr/sbin/sshd -D
      use_sudo: true
      # remove_images: true

suites:
  - name: default
    run_list:
    - recipe[starbrain::default]
    attributes:
